### PR TITLE
feature: add label property to DiscreteFilter

### LINKED ISSUE #68: Display options for filter labels
Feature Request:

Allow the options for discrete filters to have custom labels. This would allow for translations or custom formatting to be applied.

Specifically, the issue I am having is with the "Happening" field -- a special field that contains both a label and a color in the format `${label}^${color}`.  The displayed label shows the full string, where I would want to have the `^${color}` portion removed for display purposes. Having the color information is important, though, for correlating the field color with MapFilter settings.

mapfiltercolors

### PR DESCRIPTION
**Pull request by okdistribute**
fixes #68 

@GoGoCarl is this what you were thinking?

### CODE REVIEW

**Comment by GoGoCarl** [comment]
@karissa Not really, but I think I did not completely explain my full intentions in the ticket as I had discussed this with Gregor before.

I've updated the ticket to include a screenshot of what I'm talking about. So, the label I'm looking to customize is for the value of the field:

https://github.com/digidem/react-mapfilter/pull/82/files#diff-e58a7d48fe0412723727ccaef23c2184R154

That said, it WOULD be nice to be able to customize the entire filter heading as well as you have done here, but I think it would be best served if this were possible to do at a translation level. There's a `translations` map that gets initialized in MapFilter here:

https://github.com/digidem/react-mapfilter/blob/next/src/containers/MapFilter.js#L28-L43

It would be cool to be able to hook into that mapping somehow. Then, I could add my own translations for things like `field_key.happening` to have it translate in different languages.

**Comment by okdistribute** [comment]
What does your imagined API interface to hook into the translations object look like here?

**Comment by gmaclennan** [comment]
How about we allow `translations` as a prop, and deep-merge with the translations map? We could just have field_key translations and field_value translations, but I don't see harm in allowing all translations to be optionally overwritten. That way the component consumer does not need to wait for translations to be merged into react-mapfilter.

**Comment by GoGoCarl** [comment]
@karissa I think what @gmaclennan described above would work well.

**Comment by okdistribute** [comment]
@GoGoCarl ok this should work now!

**Pull request merged**
